---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 754216331960922112-eF8yY0YDevngtLTNB2iMWobiF1fMhML
:access_token_secret: jVI77Fhh8Qbb9yyF0GCt8xD5K4sl5W89Kp4zYyKCJRicj
